### ISSUE TITLE
ArrayIndexOutOfBoundsException when parsing certain HTML pages

### ISSUE THREAD

**Issue by jowerner** [Xceptance/XLT#14]
When parsing certain HTML pages, HtmlUnit may fail with this exception:

```
java.lang.ArrayIndexOutOfBoundsException: -2
	at net.sourceforge.htmlunit.cyberneko.HTMLScanner$CurrentEntity.read(HTMLScanner.java:1901)
	at net.sourceforge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scanAttribute(HTMLScanner.java:3075)
	at net.sourceforge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scanAttribute(HTMLScanner.java:2900)
	at net.sourceforge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scanStartElement(HTMLScanner.java:2747)
	at net.sourceforge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scan(HTMLScanner.java:2127)
	at net.sourceforge.htmlunit.cyberneko.HTMLScanner.scanDocument(HTMLScanner.java:937)
	at net.sourceforge.htmlunit.cyberneko.HTMLConfiguration.parse(HTMLConfiguration.java:443)
	at net.sourceforge.htmlunit.cyberneko.HTMLConfiguration.parse(HTMLConfiguration.java:394)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at com.gargoylesoftware.htmlunit.html.parser.neko.HtmlUnitNekoDOMBuilder.parse(HtmlUnitNekoDOMBuilder.java:758)
	at com.gargoylesoftware.htmlunit.html.parser.neko.HtmlUnitNekoHtmlParser.parse(HtmlUnitNekoHtmlParser.java:236)
	at com.gargoylesoftware.htmlunit.html.parser.neko.HtmlUnitNekoHtmlParser.parseHtml(HtmlUnitNekoHtmlParser.java:179)
	at com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:280)
	at com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:163)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:554)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:420)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:337)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:489)
	at com.gargoylesoftware.htmlunit.ParserTest.test(ParserTest.java:20)
```

Looks like a problem in Neko. A similar issue is already tracked for Neko: https://github.com/HtmlUnit/htmlunit-neko/issues/5

**Comment by jowerner** [comment]
Fortunately, the issue in Neko is already fixed and released, so we can try updating the Neko library and see if our issue is gone as well.
