### ISSUE TITLE
Master controller stuck while downloading results

### ISSUE THREAD

**Issue by jowerner** [Xceptance/XLT#161]
When downloading the results of a load test in non-interactive mode (i.e. via `mastercontroller.sh -c download`), the master controller printed the following to the console and eventually got stuck:

```
Xceptance LoadTest 5.7.0 (rc1967ef97c)
Copyright (c) 2005-2021 Xceptance Software Technologies GmbH. All rights reserved.
XLT is Open Source and available under the Apache License 2.0.


Checking for agent controller reachability and XLT version conflicts ... OK

Downloading test results... Please be patient, it might take some time...
    0% ... 10% ... 20% ... 30% ... 40% ... [19.692s][warning][gc,alloc] AC-communication-download-pool108: Retried waiting for GCLocker too often allocating 2052 words
[19.692s][warning][gc,alloc] AC-communication-download-pool100: Retried waiting for GCLocker too often allocating 1026 words
[19.692s][warning][gc,alloc] AC-communication-download-pool43: Retried waiting for GCLocker too often allocating 1026 words
[19.692s][warning][gc,alloc] AC-communication-download-pool0: Retried waiting for GCLocker too often allocating 1725 words
[19.692s][warning][gc,alloc] HandshakeCompletedNotify-Thread: Retried waiting for GCLocker too often allocating 4523 words
[19.692s][warning][gc,alloc] AC-communication-download-pool179: Retried waiting for GCLocker too often allocating 2050 words
Exception in thread "AC-communication-download-pool179" java.lang.OutOfMemoryError: Java heap space
Exception in thread "AC-communication-download-pool43" java.lang.OutOfMemoryError: Java heap space
Exception in thread "AC-communication-download-pool108" java.lang.OutOfMemoryError: Java heap space
	at java.base/com.sun.crypto.provider.CipherCore.prepareInputBuffer(Unknown Source)
	at java.base/com.sun.crypto.provider.CipherCore.doFinal(Unknown Source)
	at java.base/com.sun.crypto.provider.AESCipher.engineDoFinal(Unknown Source)
	at java.base/javax.crypto.CipherSpi.bufferCrypt(Unknown Source)
	at java.base/javax.crypto.CipherSpi.engineDoFinal(Unknown Source)
	at java.base/javax.crypto.Cipher.doFinal(Unknown Source)
	at java.base/sun.security.ssl.SSLCipher$T13GcmReadCipherGenerator$GcmReadCipher.decrypt(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(Unknown Source)
	at java.base/java.io.BufferedInputStream.read1(Unknown Source)
	at java.base/java.io.BufferedInputStream.read(Unknown Source)
	at java.base/sun.net.www.MeteredStream.read(Unknown Source)
	at java.base/java.io.FilterInputStream.read(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1158)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:878)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1135)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:854)
	at com.xceptance.xlt.agentcontroller.FileManagerProxy.downloadFile(FileManagerProxy.java:94)
	at com.xceptance.xlt.mastercontroller.ResultDownloader.downloadTestResults(ResultDownloader.java:511)
	at com.xceptance.xlt.mastercontroller.ResultDownloader.access$400(ResultDownloader.java:47)
	at com.xceptance.xlt.mastercontroller.ResultDownloader$4.call(ResultDownloader.java:404)
	at com.xceptance.xlt.mastercontroller.Poll$1.run(Poll.java:91)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Exception in thread "AC-communication-download-pool100" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.io.BufferedOutputStream.<init>(Unknown Source)
	at java.base/java.io.BufferedOutputStream.<init>(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source)
	at com.caucho.hessian.client.HessianURLConnection.getOutputStream(HessianURLConnection.java:97)
	at com.caucho.hessian.client.HessianProxy.sendRequest(HessianProxy.java:286)
	at com.caucho.hessian.client.HessianProxy.invoke(HessianProxy.java:171)
	at com.sun.proxy.$Proxy3.isArchiveAvailable(Unknown Source)
	at com.xceptance.xlt.agentcontroller.AgentControllerProxy.isArchiveAvailable(AgentControllerProxy.java:260)
	at com.xceptance.xlt.mastercontroller.ResultDownloader$4.call(ResultDownloader.java:400)
	at com.xceptance.xlt.mastercontroller.Poll$1.run(Poll.java:91)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
50% ... 60% ... 70% ... 80% ... 90% ... 100% Exception in thread "AC-communication-download-pool2" java.lang.IllegalArgumentException: Count must be one of [0 .. 1320] but was '1322'
	at com.xceptance.xlt.util.ProgressBar.setCount(ProgressBar.java:111)
	at com.xceptance.xlt.util.ProgressBar.increaseCount(ProgressBar.java:84)
	at com.xceptance.xlt.mastercontroller.Poll.finishAgentControllerPolling(Poll.java:149)
	at com.xceptance.xlt.mastercontroller.Poll.access$100(Poll.java:29)
	at com.xceptance.xlt.mastercontroller.Poll$1.run(Poll.java:105)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Exception in thread "AC-communication-download-pool176" java.lang.IllegalArgumentException: Count must be one of [0 .. 1320] but was '1324'
	at com.xceptance.xlt.util.ProgressBar.setCount(ProgressBar.java:111)
	at com.xceptance.xlt.util.ProgressBar.increaseCount(ProgressBar.java:84)
	at com.xceptance.xlt.mastercontroller.Poll.finishAgentControllerPolling(Poll.java:149)
	at com.xceptance.xlt.mastercontroller.Poll.access$100(Poll.java:29)
	at com.xceptance.xlt.mastercontroller.Poll$1.run(Poll.java:105)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by jowerner** [comment]
For completeness, the thread dump:

```
Full thread dump OpenJDK 64-Bit Server VM (11.0.11+9 mixed mode):

Threads class SMR info:
_java_thread_list=0x00007ff1d0004320, length=10, elements={
0x00007ff214029000, 0x00007ff2141ad800, 0x00007ff2141af800, 0x00007ff2141c4800,
0x00007ff2141c6800, 0x00007ff2141c8800, 0x00007ff2141cd000, 0x00007ff2141ce800,
0x00007ff214256000, 0x00007ff2148db800
}

"main" #1 prio=5 os_prio=0 cpu=626.25ms elapsed=6466.07s tid=0x00007ff214029000 nid=0x365 waiting on condition  [0x00007ff21be7d000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.11/Native Method)
	- parking to wait for  <0x0000000704e60dd8> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.11/Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.11/Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(java.base@11.0.11/Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(java.base@11.0.11/Unknown Source)
	at java.util.concurrent.CountDownLatch.await(java.base@11.0.11/Unknown Source)
	at com.xceptance.xlt.mastercontroller.Poll.poll(Poll.java:131)
	at com.xceptance.xlt.mastercontroller.ResultDownloader.downloadResults(ResultDownloader.java:395)
	at com.xceptance.xlt.mastercontroller.ResultDownloader.download(ResultDownloader.java:98)
	at com.xceptance.xlt.mastercontroller.MasterController.downloadTestResults(MasterController.java:317)
	at com.xceptance.xlt.mastercontroller.BasicConsoleUI.downloadTestResults(BasicConsoleUI.java:177)
	at com.xceptance.xlt.mastercontroller.NonInteractiveUI.download(NonInteractiveUI.java:268)
	at com.xceptance.xlt.mastercontroller.NonInteractiveUI.run(NonInteractiveUI.java:175)
	at com.xceptance.xlt.mastercontroller.Main.run(Main.java:615)
	at com.xceptance.xlt.mastercontroller.Main.main(Main.java:630)

"Reference Handler" #2 daemon prio=10 os_prio=0 cpu=5.13ms elapsed=6466.06s tid=0x00007ff2141ad800 nid=0x36c waiting on condition  [0x00007ff1fd399000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.ref.Reference.waitForReferencePendingList(java.base@11.0.11/Native Method)
	at java.lang.ref.Reference.processPendingReferences(java.base@11.0.11/Unknown Source)
	at java.lang.ref.Reference$ReferenceHandler.run(java.base@11.0.11/Unknown Source)

"Finalizer" #3 daemon prio=8 os_prio=0 cpu=4.18ms elapsed=6466.06s tid=0x00007ff2141af800 nid=0x36d in Object.wait()  [0x00007ff1fd298000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.11/Native Method)
	- waiting on <no object reference available>
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.11/Unknown Source)
	- waiting to re-lock in wait() <0x00000007003f3a10> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.11/Unknown Source)
	at java.lang.ref.Finalizer$FinalizerThread.run(java.base@11.0.11/Unknown Source)

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 cpu=0.24ms elapsed=6466.05s tid=0x00007ff2141c4800 nid=0x36e waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #5 daemon prio=9 os_prio=0 cpu=0.11ms elapsed=6466.05s tid=0x00007ff2141c6800 nid=0x36f runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #6 daemon prio=9 os_prio=0 cpu=9077.26ms elapsed=6466.05s tid=0x00007ff2141c8800 nid=0x370 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"C1 CompilerThread0" #8 daemon prio=9 os_prio=0 cpu=2184.15ms elapsed=6466.05s tid=0x00007ff2141cd000 nid=0x371 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"Sweeper thread" #9 daemon prio=9 os_prio=0 cpu=5.70ms elapsed=6466.05s tid=0x00007ff2141ce800 nid=0x372 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Common-Cleaner" #10 daemon prio=8 os_prio=0 cpu=6.98ms elapsed=6466.02s tid=0x00007ff214256000 nid=0x373 in Object.wait()  [0x00007ff1fc9ad000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.11/Native Method)
	- waiting on <no object reference available>
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.11/Unknown Source)
	- waiting to re-lock in wait() <0x00000007003f3830> (a java.lang.ref.ReferenceQueue$Lock)
	at jdk.internal.ref.CleanerImpl.run(java.base@11.0.11/Unknown Source)
	at java.lang.Thread.run(java.base@11.0.11/Unknown Source)
	at jdk.internal.misc.InnocuousThread.run(java.base@11.0.11/Unknown Source)

"org.apache.commons.vfs2.cache.SoftRefFilesCache$SoftRefReleaseThread" #11 daemon prio=5 os_prio=0 cpu=260.92ms elapsed=6465.68s tid=0x00007ff2148db800 nid=0x376 in Object.wait()  [0x00007ff1b7ffe000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.11/Native Method)
	- waiting on <no object reference available>
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.11/Unknown Source)
	- waiting to re-lock in wait() <0x00000007003f3d28> (a java.lang.ref.ReferenceQueue$Lock)
	at org.apache.commons.vfs2.cache.SoftRefFilesCache$SoftRefReleaseThread.run(SoftRefFilesCache.java:74)

"VM Thread" os_prio=0 cpu=606.58ms elapsed=6466.06s tid=0x00007ff2141a5000 nid=0x36b runnable  

"GC Thread#0" os_prio=0 cpu=356.84ms elapsed=6466.07s tid=0x00007ff214040800 nid=0x366 runnable  

"GC Thread#1" os_prio=0 cpu=355.04ms elapsed=6465.66s tid=0x00007ff1d8001000 nid=0x377 runnable  

"GC Thread#2" os_prio=0 cpu=352.65ms elapsed=6465.66s tid=0x00007ff1d8002800 nid=0x378 runnable  

"GC Thread#3" os_prio=0 cpu=351.02ms elapsed=6465.66s tid=0x00007ff1d8004800 nid=0x379 runnable  

"GC Thread#4" os_prio=0 cpu=320.09ms elapsed=6461.47s tid=0x00007ff1d9672800 nid=0x4f5 runnable  

"GC Thread#5" os_prio=0 cpu=230.36ms elapsed=6457.05s tid=0x00007ff1da8d8000 nid=0x958 runnable  

"G1 Main Marker" os_prio=0 cpu=0.71ms elapsed=6466.07s tid=0x00007ff214081000 nid=0x367 runnable  

"G1 Conc#0" os_prio=0 cpu=22.13ms elapsed=6466.07s tid=0x00007ff214083000 nid=0x368 runnable  

"G1 Conc#1" os_prio=0 cpu=21.60ms elapsed=6457.76s tid=0x00007ff1e8003800 nid=0x8a4 runnable  

"G1 Refine#0" os_prio=0 cpu=4.75ms elapsed=6466.07s tid=0x00007ff214148000 nid=0x369 runnable  

"G1 Young RemSet Sampling" os_prio=0 cpu=1104.10ms elapsed=6466.07s tid=0x00007ff21414a000 nid=0x36a runnable  
"VM Periodic Task Thread" os_prio=0 cpu=2715.07ms elapsed=6466.02s tid=0x00007ff21425a000 nid=0x374 waiting on condition  

JNI global refs: 20, weak refs: 0

Heap
 garbage-first heap   total 592896K, used 148455K [0x0000000700000000, 0x0000000800000000)
  region size 1024K, 37 young (37888K), 6 survivors (6144K)
 Metaspace       used 21485K, capacity 21808K, committed 22144K, reserved 1069056K
  class space    used 2254K, capacity 2357K, committed 2432K, reserved 1048576K
```

**Comment by jowerner** [comment]
See also #164.

**Comment by rschwietzke** [comment]
Likely solved.
