### ISSUE TITLE
Make XLT run with JDK13 or higher

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/XLT#2]
JDK13 brings a new socket impl by default and the current instrumentation fails.

**Comment by jowerner** [comment]
See https://openjdk.java.net/jeps/353 for more details about the new socket implementation. Also note that the old socket impl is still available. If you experience issues with the new impl, set the system property `-Djdk.net.usePlainSocketImpl`.

**Comment by jowerner** [comment]
Adapted our code to handle both the old and the new socket impl depending on the JRE being used and the presence of system property `jdk.net.usePlainSocketImpl`. Note that API-wise the old impl in Java 13 has changed a bit as well compared with Java 8, so different code branches are needed.

**Comment by randolph-straub** [comment]
Tested on Ubuntu 18.04 with java 11.0.2, 13.0.2 and 14.0.1. Works with java 11 but failed for java 13 and 14 with some permission errors for embedded mode and using dedicated agent controller. The logs for java 13 and 14 are showing the following errors.

**Embedded Mode**
`
[2020/04/16-08:57:56,325] ERROR [AC-communication-default-pool0] com.xceptance.xlt.mastercontroller.MasterController - Failed starting agents at embedded
java.lang.RuntimeException: java.io.IOException: Cannot run program "./xlt-5.1.0-SNAPSHOT/bin/agent.sh" (in directory "./xlt-5.1.0-SNAPSHOT/agent/embedded_00"): error=13, Permission denied
	at com.xceptance.xlt.agentcontroller.AgentControllerImpl.startAgents(AgentControllerImpl.java:705)
	at com.xceptance.xlt.mastercontroller.MasterController$4.run(MasterController.java:893)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.io.IOException: Cannot run program "./xlt-5.1.0-SNAPSHOT/bin/agent.sh" (in directory "./xlt-5.1.0-SNAPSHOT/agent/embedded_00"): error=13, Permission denied
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.xceptance.xlt.agentcontroller.AgentImpl.<init>(AgentImpl.java:114)
	at com.xceptance.xlt.agentcontroller.AgentManagerImpl.startAgent(AgentManagerImpl.java:146)
	at com.xceptance.xlt.agentcontroller.AgentControllerImpl.startAgents(AgentControllerImpl.java:701)
	... 4 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:319)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:250)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 8 more
`

**Agentcontroller**
`
[2020/04/16-09:02:00,917] ERROR [AC-communication-default-pool1] com.xceptance.xlt.mastercontroller.MasterController - Failed starting agents at Agent Controller ac001 <https://localhost:8500>
java.lang.RuntimeException: java.io.IOException: Cannot run program "./xlt-5.1.0-SNAPSHOT/bin/agent.sh" (in directory "./xlt-5.1.0-SNAPSHOT/agent/ac001_00"): error=13, Permission denied
	at com.xceptance.xlt.agentcontroller.AgentControllerImpl.startAgents(AgentControllerImpl.java:705)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.caucho.hessian.server.HessianSkeleton.invoke(HessianSkeleton.java:302)
	at com.caucho.hessian.server.HessianSkeleton.invoke(HessianSkeleton.java:198)
	at com.caucho.hessian.server.HessianServlet.invoke(HessianServlet.java:428)
	at com.caucho.hessian.server.HessianServlet.service(HessianServlet.java:408)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:755)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:547)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:555)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1300)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1215)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:543)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:398)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:161)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.io.IOException: Cannot run program "./xlt-5.1.0-SNAPSHOT/bin/agent.sh" (in directory "./xlt-5.1.0-SNAPSHOT/agent/ac001_00"): error=13, Permission denied
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.xceptance.xlt.agentcontroller.AgentImpl.<init>(AgentImpl.java:114)
	at com.xceptance.xlt.agentcontroller.AgentManagerImpl.startAgent(AgentManagerImpl.java:146)
	at com.xceptance.xlt.agentcontroller.AgentControllerImpl.startAgents(AgentControllerImpl.java:701)
	... 44 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:319)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:250)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 48 more
`
