### ISSUE TITLE
Unknown charset exception

### ISSUE THREAD

**Issue by jowerner** [Xceptance/XLT#201]
A test case may fail unexpectedly on certain machines with an exception similar to this one:

```
java.lang.ExceptionInInitializerError: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at java.lang.Class.newInstance(Class.java:584) ~[?:?]
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.configureClass(JavaScriptEngine.java:597) ~[classes/:?]
    ...
Caused by: java.nio.charset.UnsupportedCharsetException: Big5
	at java.nio.charset.Charset.forName(Charset.java:529) ~[?:?]
	at com.gargoylesoftware.htmlunit.javascript.host.TextDecoder.<clinit>(TextDecoder.java:61) ~[classes/:?]
	... 59 more  
```

Looks like HU expects certain charsets to exist on every platform, but this is not the case.

**Comment by jowerner** [comment]
Fixed by ignoring charsets that do not exist on the local platform.
